version: "3.8"

services:
  app:
    build:
      context: .
    ports: 
      - "5050"
    deploy:
      replicas: 2
  
  nginx:
    image: nginx:latest
    ports:
      - "5055:5055"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data

volumes:
    redis-data:
